name: QA Automation CI

on:
  push:
    branches:
      - main
      - backup-ecommerce-final
      - feature/**
  pull_request:
    branches:
      - main
      - backup-ecommerce-final

jobs:
  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-rerunfailures

      - name: Install Microsoft Edge
        uses: browser-actions/setup-edge@v1

      - name: Run tests
        env:
          CI: true
          BROWSER: edge
        run: |
          pytest --reruns 2
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots/
